# Gush configuration file, any comments will be lost.
table-pr:
    bug_fix: ['Bug Fix?', 'no']
    new_feature: ['New Feature?', 'no']
    bc_breaks: ['BC Breaks?', 'no']
    deprecations: ['Deprecations?', 'no']
    fixed_tickets: ['Fixed Tickets', '']
    license: [License, MIT]
repo_adapter: github
issue_tracker: github
repo_org: rollerworks
repo_name: rollerworks-metadata
issue_project_org: rollerworks
issue_project_name: rollerworks-metadata
